
def summarize_and_format(grouped_data):
    """
    Takes a dictionary of {source_name: {summary: str, items: [list]}}
    Returns an HTML string.
    """
    if not grouped_data:
        return "<p>No new items found.</p>"

    html = "<html><body style='font-family: Arial, sans-serif; color: #333;'>"
    html += "<h2 style='color: #2c3e50;'>📅 Daily Info Tracker Report</h2>\n"
    
    for source, data in grouped_data.items():
        summary = data.get('summary')
        items = data.get('items', [])
        
        if not items: continue

        html += f"<h3 style='color: #d35400; margin-top: 20px; margin-bottom: 5px;'>{source}</h3>\n"

        # AI Summary Logic
        if summary:
            briefing = summary
            filtered_log = ""
            
            if isinstance(summary, str) and "## Filtered Log" in summary:
                parts = summary.split("## Filtered Log")
                briefing = parts[0].replace("## Briefing", "").replace("報告老闆，", "").strip()
                filtered_log = parts[1].strip()
            
            if briefing and "nothing significant" not in briefing.lower():
                html += "<strong>🤖 AI 綜合報告:</strong><br/>\n"
                html += f"<div style='margin-bottom: 10px; line-height: 1.5;'>{briefing}</div>\n"
            
            # Print the filtered log exactly as requested (e.g. "請問這段程式碼為什麼會報錯？(This should be filtered) (2 hrs ago)")
            if filtered_log:
                # Basic parsing to look somewhat resembling lists if necessary
                lines = filtered_log.strip().split('\n')
                for line in lines:
                    line = line.strip()
                    if line.startswith("- "):
                        line = line[2:] # Remove bullet
                        # Format as requested: Title (Reason)
                        if "]: [" in line:
                            title_part = line.split("]: [")[0].replace("[", "").strip()
                            reason_part = line.split("]: [")[1].replace("]", "").strip()
                            html += f"<div style='color: #7f8c8d; margin-bottom: 5px;'>{title_part} ({reason_part}) (Recent)</div>\n"
                        else:
                            html += f"<div style='color: #7f8c8d; margin-bottom: 5px;'>{line}</div>\n"

        # Original Links (The non-filtered items)
        for item in items:
            title = item.get('title', 'No Title')
            link = item.get('link', '#')
            date = item.get('date', 'Recent')
            html += f"<div style='margin-bottom: 5px;'><a href='{link}' style='text-decoration: none; color: #2980b9;'>{title}</a> <span style='font-size: 0.9em; color: #7f8c8d;'>({date})</span></div>\n"

    html += "<div style='margin-top: 30px; font-size: 0.8em; color: #bdc3c7;'>Generated by Info Tracker Bot</div>\n"
    html += "</body></html>"
    
    return html
