
def summarize_and_format(grouped_data):
    """
    Takes a dictionary of {source_name: {summary: str, items: [list]}}
    Returns an HTML string.
    """
    if not grouped_data:
        return "<p>No new items found.</p>"

    html = "<html><body>"
    html += "<h2>📅 Daily Info Tracker Report</h2>"
    
    for source, data in grouped_data.items():
        summary = data.get('summary')
        items = data.get('items', [])
        
        if not items: continue

        if not summary:
            # If AI failed or returned None, skip this source group
            continue
            
        # Split Summary and Filtered Log
        briefing = summary
        filtered_log = ""
        
        if isinstance(summary, str) and "## Filtered Log" in summary:
            parts = summary.split("## Filtered Log")
            briefing = parts[0].replace("## Briefing", "").strip()
            filtered_log = parts[1].strip()
        
        # 1. AI Aggregated Summary (Briefing)
        if briefing and "nothing significant" not in briefing.lower():
            html += f"<div style='background-color: #f9f9f9; padding: 15px; border-left: 4px solid #3498db; margin-bottom: 15px; color: #444; line-height: 1.6;'>"
            html += f"<strong>🤖 AI 綜合報告:</strong><br/>{briefing}"
            html += "</div>"
        
        # 2. Filtered Log (Collapsible)
        if filtered_log:
            html += f"<details style='margin-bottom: 15px; color: #7f8c8d; font-size: 0.9em;'>"
            html += f"<summary style='cursor: pointer;'>🗑️ 查看已過濾內容 (Filtered Items)</summary>"
            html += f"<pre style='white-space: pre-wrap; background: #eee; padding: 10px; margin-top: 5px; border-radius: 4px;'>{filtered_log}</pre>"
            html += f"</details>"
        
        # 3. Original Links
        html += "<ul style='padding-left: 20px; color: #666;'>"
        for item in items:
            title = item.get('title', 'No Title')
            link = item.get('link', '#')
            date = item.get('date', '')
            html += f"<li style='margin-bottom: 5px;'><a href='{link}' style='text-decoration: none; color: #2980b9;'>{title}</a> <span style='font-size: 0.8em; color: #999;'>({date})</span></li>"
        html += "</ul>"
        html += "</div>"

    html += "<p style='font-size: 0.8em; color: #999;'>Generated by Info Tracker Bot</p>"
    html += "</body></html>"
    
    return html
