
def summarize_and_format(grouped_data):
    """
    Takes a dictionary of {source_name: {summary: str, items: [list]}}
    Returns an HTML string.
    """
    if not grouped_data:
        return "<p>No new items found.</p>"

    html = "<html><body style='font-family: Arial, sans-serif; color: #333; line-height: 1.5;'>"
    html += "<h2 style='color: #2c3e50;'>📅 Daily Info Tracker Report</h2>\n"
    
    for source, data in grouped_data.items():
        summary = data.get('summary')
        items = data.get('items', [])
        
        if not items: continue

        html += f"<h3 style='color: #2c3e50; margin-top: 30px; margin-bottom: 15px;'>{source}</h3>\n"

        # AI Summary Logic
        briefing = ""
        filtered_log = ""
        
        if summary:
            if isinstance(summary, str) and "## Filtered Log" in summary:
                parts = summary.split("## Filtered Log")
                briefing = parts[0].replace("## Briefing", "").replace("報告老闆，", "").strip()
                filtered_log = parts[1].strip()
            else:
                briefing = summary.strip()
            
            if briefing and "nothing significant" not in briefing.lower():
                html += f"<div style='background-color: #f9f9f9; padding: 15px; border-left: 4px solid #3498db; margin-bottom: 15px; color: #444; line-height: 1.6;'>"
                html += f"<strong>🤖 AI 綜合報告:</strong><br/>{briefing}"
                html += "</div>\n"
        
        html += "<ul style='padding-left: 20px; color: #666; margin-top: 10px;'>\n"

        # Print the filtered log
        if filtered_log:
            lines = filtered_log.split('\n')
            for line in lines:
                line = line.strip()
                if line.startswith("- "):
                    line = line[2:] # Remove bullet
                    if "]: [" in line:
                        title_part = line.split("]: [")[0].replace("[", "").strip()
                        reason_part = line.split("]: [")[1].replace("]", "").strip()
                        html += f"<li style='margin-bottom: 8px; color: #7f8c8d;'>{title_part} ({reason_part})</li>\n"
                    else:
                        html += f"<li style='margin-bottom: 8px; color: #7f8c8d;'>{line}</li>\n"

        # Original Links (The non-filtered items)
        for item in items:
            title = item.get('title', 'No Title')
            link = item.get('link') or item.get('url') or '#'
            date = item.get('date', 'Recent')
            html += f"<li style='margin-bottom: 8px;'><a href='{link}' style='text-decoration: none; color: #2980b9;'>{title}</a> <span style='font-size: 0.8em; color: #999;'>({date})</span></li>\n"

        html += "</ul>\n"

    html += "<div style='margin-top: 40px; font-size: 0.8em; color: #bdc3c7;'>Generated by Info Tracker Bot</div>\n"
    html += "</body></html>"
    
    return html
